#!/usr/bin/env python3
"""Generate NETLIST.md, bom/BOM.csv and bom/CPL-positions.csv from design.py
plus the placed board (positions/rotations for the CPL).

Run with:
  LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/bin/python3 gen_docs.py
"""
import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, HERE)
import design

design.validate()

# ------------------------------------------------------------- NETLIST.md
pin_net = {}
for net, pads in design.NETS.items():
    for rp in pads:
        pin_net[rp] = net
nc = set(design.NC)

lines = []
lines.append("# Esp32Tap NETLIST — source of truth")
lines.append("")
lines.append("Generated by `tools/gen_docs.py` from `tools/design.py`.  The KiCad")
lines.append("schematic and board are generated from the *same* tables, and the")
lines.append("build scripts assert exact parity (schematic netlist export and board")
lines.append("pad-net assignment are diffed against these tables).  If you edit the")
lines.append("design, edit `tools/design.py` and regenerate everything.")
lines.append("")
lines.append("## Components")
lines.append("")
lines.append("| Ref | Value | Footprint | LCSC | JLC class | Description |")
lines.append("|-----|-------|-----------|------|-----------|-------------|")
for ref, c in design.COMPONENTS.items():
    val, flib, fname, lcsc, jclass, cost, desc, pins = c
    lines.append(f"| {ref} | {val} | {flib}:{fname} | {lcsc or '-'} | {jclass} | {desc} |")
lines.append("")
lines.append("## Nets")
lines.append("")
lines.append("Every connection on the board.  `ref.pad (pin-name)` format.")
lines.append("")
for net, pads in design.NETS.items():
    ent = ", ".join(f"`{r}.{p}` ({design.COMPONENTS[r][7][p]})" for r, p in pads)
    lines.append(f"* **{net}** — {ent}")
lines.append("")
lines.append("## Deliberately unconnected pins")
lines.append("")
ncl = ", ".join(f"`{r}.{p}`" for r, p in design.NC)
lines.append(ncl)
lines.append("")
lines.append("## Key wiring facts")
lines.append("")
lines.append("* **Fail-safe relay K1** (Omron G6K-2F-Y, coil 1/8, pole A COM=3 NC=2 NO=4,")
lines.append("  pole B COM=6 NC=7 NO=5): de-energized, both poles bridge console pin 6")
lines.append("  (CONS6) to motor pin 6 (MOT6) **and physically disconnect the ESP32 TX**")
lines.append("  (which sits on the NO contacts).  Unpowered/crashed board = stock")
lines.append("  treadmill.  Energized (Emulate only), MOT6 is driven by ESP TX via R6")
lines.append("  and the console line is released (only the 4.7k RX tap remains on it).")
lines.append("* **RX taps are 4.7k** (R7 console pin 6, R8 pin 3) so a dead 3.3V rail")
lines.append("  back-feeds <0.3mA through the GPIO clamp diodes — bus levels intact.")
lines.append("* **ESD clamps D5/D6/D7 are PESD3V3L1BA to GND only** (bidirectional,")
lines.append("  not rail-referenced) — inert when the board is unpowered.")
lines.append("* **Pass-through pins**: RJ45 1,2,4,5,7,8 are pure copper between J1 and")
lines.append("  J2 (pin 5 safety interlock and unknown pin 4 never touch silicon).")
lines.append("* **VIN ORing**: 8V rail (D1) or USB VBUS (D2) feed the TPS54202 buck —")
lines.append("  bench flashing needs no treadmill.")
lines.append("* GPIO map: IO17=UART1 TX (motor pin6), IO18=UART1 RX (console pin6),")
lines.append("  IO16=UART2 RX (pin3 tap), IO21=relay driver, IO38=status LED.")
lines.append("  None are ESP32-S3 strap pins (0/3/45/46) or the USB pins (19/20).")
lines.append("")

with open(os.path.join(ROOT, "NETLIST.md"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote NETLIST.md")

# ------------------------------------------------------------- BOM.csv
os.makedirs(os.path.join(ROOT, "bom"), exist_ok=True)
groups = {}
for ref, c in design.COMPONENTS.items():
    val, flib, fname, lcsc, jclass, cost, desc, pins = c
    if jclass == "none":
        continue  # test points: no part fitted
    key = (val, fname, lcsc)
    groups.setdefault(key, {"refs": [], "jclass": jclass, "cost": cost, "desc": desc})["refs"].append(ref)

with open(os.path.join(ROOT, "bom", "BOM.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(
        [
            "Comment",
            "Designator",
            "Footprint",
            "LCSC Part #",
            "JLC class",
            "Qty",
            "Unit cost (USD)",
            "Ext cost (USD)",
            "Description",
        ]
    )
    total = 0.0
    for (val, fname, lcsc), g in groups.items():
        qty = len(g["refs"])
        ext = qty * g["cost"]
        total += ext
        w.writerow(
            [val, ",".join(g["refs"]), fname, lcsc, g["jclass"], qty, f"{g['cost']:.3f}", f"{ext:.3f}", g["desc"]]
        )
    # NOTE: no trailing "TOTAL" row — the file must stay JLC-BOM-tool clean.
    # The per-board parts total lives in ORDERING.md (and is printed below).
print(f"wrote bom/BOM.csv (parts/board ≈ ${total:.2f} — keep ORDERING.md's figure in sync)")

# ------------------------------------------------------------- CPL
import pcbnew  # noqa: E402

b = pcbnew.LoadBoard(os.path.join(ROOT, "kicad", "Esp32Tap.kicad_pcb"))
aux_origin_x, aux_origin_y = 100.0, 155.0  # board bottom-left in sheet coords
with open(os.path.join(ROOT, "bom", "CPL-positions.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Designator", "Val", "Package", "Mid X", "Mid Y", "Rotation", "Layer"])
    for fp in sorted(b.GetFootprints(), key=lambda x: x.GetReference()):
        ref = fp.GetReference()
        if ref.startswith(("TP", "MH")):
            continue  # nothing to place
        p = fp.GetPosition()
        x = pcbnew.ToMM(p.x) - aux_origin_x
        y = aux_origin_y - pcbnew.ToMM(p.y)  # JLC: +y up from bottom-left
        w.writerow(
            [
                ref,
                fp.GetValue(),
                fp.GetFPID().GetLibItemName(),
                f"{x:.3f}mm",
                f"{y:.3f}mm",
                f"{fp.GetOrientationDegrees():.0f}",
                "Top",
            ]
        )
print("wrote bom/CPL-positions.csv")
