#!/usr/bin/env python3
"""Generate Rev C NETLIST, BOM, and optionally CPL files from design.py.

The NETLIST and BOM require only the standard Python runtime.  CPL generation
additionally reads the placed KiCad board through pcbnew and can be disabled
with ``--skip-cpl`` while the Rev C PCB is not yet available.
"""

from __future__ import annotations

import argparse
import csv
import io
import os
import tempfile
from pathlib import Path
from typing import Any

import design

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def parse_args(arguments: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Esp32Tap Rev C NETLIST.md and BOM.csv; generate the " "placed-board CPL unless --skip-cpl is set."
        )
    )
    parser.add_argument(
        "--skip-cpl",
        action="store_true",
        help=("do not import pcbnew and do not create or modify " "bom/CPL-positions.csv"),
    )
    return parser.parse_args(arguments)


def render_netlist() -> str:
    """Render the human-readable design table and Rev C topology notes."""
    lines = [
        "# Esp32Tap Rev C NETLIST — generated design record",
        "",
        "`tools/design.py` is the source of truth. Generated by " "`tools/gen_docs.py`;",
        "the schematic and PCB generators consume the same component, pin, " "and net tables.",
        "Edit `tools/design.py`, validate it, and regenerate the artifacts " "instead of",
        "hand-editing this file.",
        "",
        "## Components",
        "",
        "| Ref | Value | Footprint | LCSC | JLC class | Description |",
        "|-----|-------|-----------|------|-----------|-------------|",
    ]
    for reference, component in design.COMPONENTS.items():
        (
            value,
            footprint_library,
            footprint,
            lcsc,
            jlc_class,
            _cost,
            description,
            _pins,
        ) = component
        lines.append(
            f"| {reference} | {value} | "
            f"{footprint_library}:{footprint} | {lcsc or '-'} | "
            f"{jlc_class} | {description} |"
        )

    lines.extend(
        [
            "",
            "## Nets",
            "",
            "Every physical connection is listed as " "`reference.pad (pin-name)`.",
            "",
        ]
    )
    for net, pins in design.NETS.items():
        entries = ", ".join(
            f"`{reference}.{pad}` " f"({design.COMPONENTS[reference][7][pad]})" for reference, pad in pins
        )
        lines.append(f"* **{net}** — {entries}")

    no_connects = ", ".join(f"`{reference}.{pad}`" for reference, pad in design.NC)
    lines.extend(
        [
            "",
            "## Deliberately unconnected pins",
            "",
            no_connects,
            "",
            "## Rev C topology",
            "",
            "* **Power — treadmill-only local power:** J1/J2 +8V passes " "through F1",
            "  and series reverse-polarity diode D1 before reaching VIN. " "All local",
            "  regulator and supervisor power inputs are downstream of D1.",
            "* **USB is data-only:** J3 VBUS supplies USB protection, " "bypass, discharge,",
            "  and presence sensing only; it has no path into VIN or the " "local rails.",
            "* **Treadmill permission:** U4 monitors protected VIN and its " "open-drain",
            "  outputs form TREAD_OK. U6 requires TREAD_OK for both " "RELAY_GATE and",
            "  TX_GATE, so firmware commands alone cannot enable either " "path.",
            "* **TREAD_OK/IO6 isolation:** R32 is a series resistor between "
            "TREAD_OK and TREAD_OK_MCU (U1 IO6 only), so a misconfigured "
            "push-pull GPIO cannot force the interlock high or contend "
            "with U4's open-drain output; U4/U6/R21/R22/TP7 stay directly "
            "on TREAD_OK (review finding B2).",
            "* **Relay control:** U5 enables the +5V_RLY coil supply and Q1 " "enables",
            "  the low side. These are series hardware controls driven by " "RELAY_GATE;",
            "  loss of permission removes coil power.",
            "* **Relay contacts:** K1 uses one transfer pole for serial " "bypass/drive",
            "  and one dry feedback pole for K1_NC_FB/K1_NO_FB. The " "feedback pole",
            "  does not carry or duplicate the serial path.",
            "* **TX isolation:** U7 provides hardware TX isolation before " "R6 and K1;",
            "  TX_GATE must be asserted before ESP_TX can reach TX_DRV.",
            "* **Receive loading:** R7 and R8 are 10k UART taps for console " "pin 6",
            "  and pass-through pin 3, limiting back-feed into an unpowered " "MCU.",
            "* **USB tuning:** C13/C14 are DNP shunt-tuning footprints and " "are not",
            "  included in assembly outputs.",
            "* **ERC helpers:** four schematic-only power flags declare GND, " "VIN,",
            "  +3V3, and VBUS as powered after their passive entry paths. " "They have",
            "  no footprint and are excluded from BOM/CPL; they add no PCB " "copper.",
            "* **Harness interfaces:** J1 is Molex 430450809/C240838 with "
            "430250800 housing; J2 is Molex 430451010/C563827 with "
            "430251000 housing. Both use 430300001 terminals. The 8- and "
            "10-position housings are physically incompatible; J2 pads "
            "9/10 are deliberately NC.",
            "* **Release status:** "
            "PROVISIONAL_REQUIRES_LIVE_BOM_CPL_PROOF; public catalog "
            "identity is not an order-ready placement result.",
            "* **GPIO map:** IO4=K1_NC_FB, IO5=K1_NO_FB, IO6=TREAD_OK_MCU,",
            "  IO7=VBUS_PRESENT_N, IO15=TX_ENABLE, IO16=UART2 RX,",
            "  IO17=UART1 TX, IO18=UART1 RX, IO21=RELAY_CMD, " "IO38=status LED.",
            "  Native USB remains on IO19/IO20.",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def populated_component(reference: str, component: tuple[Any, ...]) -> bool:
    """Return whether a design component belongs in assembly outputs."""
    return reference not in design.DNP and component[4] != "none"


def bom_groups() -> dict[tuple[Any, ...], list[str]]:
    """Group only components with completely identical purchasing metadata."""
    groups: dict[tuple[Any, ...], list[str]] = {}
    for reference, component in design.COMPONENTS.items():
        (
            value,
            footprint_library,
            footprint,
            lcsc,
            jlc_class,
            unit_cost,
            description,
            _pins,
        ) = component
        if not populated_component(reference, component):
            continue
        key = (
            value,
            footprint_library,
            footprint,
            lcsc,
            jlc_class,
            unit_cost,
            description,
        )
        groups.setdefault(key, []).append(reference)
    return groups


def render_bom() -> tuple[str, float]:
    """Render the assembly BOM without touching its destination."""
    output = io.StringIO(newline="")
    total = 0.0
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(
        [
            "Comment",
            "Designator",
            "Footprint",
            "LCSC Part #",
            "JLC class",
            "Qty",
            "Unit cost (USD)",
            "Ext cost (USD)",
            "Description",
        ]
    )
    for key, references in bom_groups().items():
        (
            value,
            _footprint_library,
            footprint,
            lcsc,
            jlc_class,
            unit_cost,
            description,
        ) = key
        quantity = len(references)
        extended_cost = quantity * unit_cost
        total += extended_cost
        writer.writerow(
            [
                value,
                ",".join(references),
                footprint,
                lcsc,
                jlc_class,
                quantity,
                f"{unit_cost:.3f}",
                f"{extended_cost:.3f}",
                description,
            ]
        )
    return output.getvalue(), total


def load_cpl_context(root: Path) -> tuple[Any, list[Any]]:
    """Import pcbnew and load the board once before rendering any output."""
    import pcbnew

    board_path = root / "kicad" / "Esp32Tap.kicad_pcb"
    if not board_path.is_file():
        raise FileNotFoundError(f"cannot generate CPL; KiCad board does not exist: {board_path}")
    board = pcbnew.LoadBoard(str(board_path))
    if board is None:
        raise RuntimeError(f"pcbnew failed to load KiCad board: {board_path}")
    try:
        footprints = list(board.GetFootprints())
    except (AttributeError, TypeError) as error:
        raise RuntimeError(f"pcbnew loaded an invalid KiCad board: {board_path}") from error
    return pcbnew, footprints


def render_cpl(pcbnew: Any, footprints: list[Any]) -> str:
    """Render the CPL from a preflighted board without writing it."""
    output = io.StringIO(newline="")
    auxiliary_origin_x = 100.0
    auxiliary_origin_y = 155.0
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(
        [
            "Designator",
            "Val",
            "Package",
            "Mid X",
            "Mid Y",
            "Rotation",
            "Layer",
        ]
    )
    for footprint in sorted(
        footprints,
        key=lambda item: item.GetReference(),
    ):
        reference = footprint.GetReference()
        component = design.COMPONENTS.get(reference)
        if component is None or not populated_component(
            reference,
            component,
        ):
            continue
        position = footprint.GetPosition()
        x_position = pcbnew.ToMM(position.x) - auxiliary_origin_x
        y_position = auxiliary_origin_y - pcbnew.ToMM(position.y)
        rotation = footprint.GetOrientationDegrees() % 360.0
        writer.writerow(
            [
                reference,
                footprint.GetValue(),
                footprint.GetFPID().GetLibItemName(),
                f"{x_position:.3f}mm",
                f"{y_position:.3f}mm",
                f"{rotation:.0f}",
                "Top",
            ]
        )
    return output.getvalue()


def validate_staged_outputs(
    staging_directory: Path,
    include_cpl: bool,
) -> None:
    """Validate staged text and CSV shape before replacing destinations."""
    netlist_bytes = (staging_directory / "NETLIST.md").read_bytes()
    if b"\r\n" in netlist_bytes:
        raise ValueError("NETLIST.md must use LF line endings")
    netlist = netlist_bytes.decode("utf-8")
    if not netlist.startswith("# Esp32Tap Rev C NETLIST"):
        raise ValueError("staged NETLIST.md has an invalid heading")

    expected_headers = {
        Path("bom/BOM.csv"): [
            "Comment",
            "Designator",
            "Footprint",
            "LCSC Part #",
            "JLC class",
            "Qty",
            "Unit cost (USD)",
            "Ext cost (USD)",
            "Description",
        ],
    }
    if include_cpl:
        expected_headers[Path("bom/CPL-positions.csv")] = [
            "Designator",
            "Val",
            "Package",
            "Mid X",
            "Mid Y",
            "Rotation",
            "Layer",
        ]
    for relative_path, expected_header in expected_headers.items():
        content_bytes = (staging_directory / relative_path).read_bytes()
        if b"\r\n" in content_bytes:
            raise ValueError(f"{relative_path} must use LF line endings")
        content = content_bytes.decode("utf-8")
        rows = list(csv.reader(io.StringIO(content)))
        if not rows or rows[0] != expected_header:
            raise ValueError(f"{relative_path} has an invalid CSV header")


def generate_outputs(root: Path, skip_cpl: bool) -> None:
    """Preflight, render, stage, validate, then replace intended outputs."""
    cpl_context = None
    if not skip_cpl:
        cpl_context = load_cpl_context(root)

    bom, total = render_bom()
    outputs = {
        Path("NETLIST.md"): render_netlist(),
        Path("bom/BOM.csv"): bom,
    }
    if cpl_context is not None:
        pcbnew, footprints = cpl_context
        outputs[Path("bom/CPL-positions.csv")] = render_cpl(
            pcbnew,
            footprints,
        )

    root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix=".esp32tap-docs-",
        dir=root,
    ) as temporary:
        staging_directory = Path(temporary)
        for relative_path, content in outputs.items():
            staged = staging_directory / relative_path
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(
                content,
                encoding="utf-8",
                newline="\n",
            )
        validate_staged_outputs(
            staging_directory,
            include_cpl=not skip_cpl,
        )
        for relative_path in outputs:
            destination = root / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            os.replace(
                staging_directory / relative_path,
                destination,
            )

    print("wrote NETLIST.md")
    print(f"wrote bom/BOM.csv (parts/board ≈ ${total:.2f})")
    if not skip_cpl:
        print("wrote bom/CPL-positions.csv")


def main(arguments: list[str] | None = None) -> None:
    args = parse_args(arguments)
    design.validate()
    generate_outputs(ROOT, skip_cpl=args.skip_cpl)


if __name__ == "__main__":
    main()
