#!/usr/bin/env python3
"""Generate Rev B NETLIST, BOM, and optionally CPL files from design.py.

The NETLIST and BOM require only the standard Python runtime.  CPL generation
additionally reads the placed KiCad board through pcbnew and can be disabled
with ``--skip-cpl`` while the Rev B PCB is not yet available.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any

import design


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def parse_args(arguments: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Esp32Tap Rev B NETLIST.md and BOM.csv; generate the "
            "placed-board CPL unless --skip-cpl is set."
        )
    )
    parser.add_argument(
        "--skip-cpl",
        action="store_true",
        help=(
            "do not import pcbnew and do not create or modify "
            "bom/CPL-positions.csv"
        ),
    )
    return parser.parse_args(arguments)


def render_netlist() -> str:
    """Render the human-readable design table and Rev B topology notes."""
    lines = [
        "# Esp32Tap Rev B NETLIST — generated design record",
        "",
        "`tools/design.py` is the source of truth. Generated by "
        "`tools/gen_docs.py`;",
        "the schematic and PCB generators consume the same component, pin, "
        "and net tables.",
        "Edit `tools/design.py`, validate it, and regenerate the artifacts "
        "instead of",
        "hand-editing this file.",
        "",
        "## Components",
        "",
        "| Ref | Value | Footprint | LCSC | JLC class | Description |",
        "|-----|-------|-----------|------|-----------|-------------|",
    ]
    for reference, component in design.COMPONENTS.items():
        (
            value,
            footprint_library,
            footprint,
            lcsc,
            jlc_class,
            _cost,
            description,
            _pins,
        ) = component
        lines.append(
            f"| {reference} | {value} | "
            f"{footprint_library}:{footprint} | {lcsc or '-'} | "
            f"{jlc_class} | {description} |"
        )

    lines.extend(
        [
            "",
            "## Nets",
            "",
            "Every physical connection is listed as "
            "`reference.pad (pin-name)`.",
            "",
        ]
    )
    for net, pins in design.NETS.items():
        entries = ", ".join(
            f"`{reference}.{pad}` "
            f"({design.COMPONENTS[reference][7][pad]})"
            for reference, pad in pins
        )
        lines.append(f"* **{net}** — {entries}")

    no_connects = ", ".join(
        f"`{reference}.{pad}`"
        for reference, pad in design.NC
    )
    lines.extend(
        [
            "",
            "## Deliberately unconnected pins",
            "",
            no_connects,
            "",
            "## Rev B topology",
            "",
            "* **Power — treadmill-only local power:** J1/J2 +8V passes "
            "through F1",
            "  and series reverse-polarity diode D1 before reaching VIN. "
            "All local",
            "  regulator and supervisor power inputs are downstream of D1.",
            "* **USB is data-only:** J3 VBUS supplies USB protection, "
            "bypass, discharge,",
            "  and presence sensing only; it has no path into VIN or the "
            "local rails.",
            "* **Treadmill permission:** U4 monitors protected VIN and its "
            "open-drain",
            "  outputs form TREAD_OK. U6 requires TREAD_OK for both "
            "RELAY_GATE and",
            "  TX_GATE, so firmware commands alone cannot enable either "
            "path.",
            "* **Relay control:** U5 enables the +5V_RLY coil supply and Q1 "
            "enables",
            "  the low side. These are series hardware controls driven by "
            "RELAY_GATE;",
            "  loss of permission removes coil power.",
            "* **Relay contacts:** K1 uses one transfer pole for serial "
            "bypass/drive",
            "  and one dry feedback pole for K1_NC_FB/K1_NO_FB. The "
            "feedback pole",
            "  does not carry or duplicate the serial path.",
            "* **TX isolation:** U7 provides hardware TX isolation before "
            "R6 and K1;",
            "  TX_GATE must be asserted before ESP_TX can reach TX_DRV.",
            "* **Receive loading:** R7 and R8 are 10k UART taps for console "
            "pin 6",
            "  and pass-through pin 3, limiting back-feed into an unpowered "
            "MCU.",
            "* **USB tuning:** C13/C14 are DNP shunt-tuning footprints and "
            "are not",
            "  included in assembly outputs.",
            "* **ERC helpers:** four schematic-only power flags declare GND, "
            "VIN,",
            "  +3V3, and VBUS as powered after their passive entry paths. "
            "They have",
            "  no footprint and are excluded from BOM/CPL; they add no PCB "
            "copper.",
            "* **GPIO map:** IO4=K1_NC_FB, IO5=K1_NO_FB, IO6=TREAD_OK,",
            "  IO7=VBUS_PRESENT_N, IO15=TX_ENABLE, IO16=UART2 RX,",
            "  IO17=UART1 TX, IO18=UART1 RX, IO21=RELAY_CMD, "
            "IO38=status LED.",
            "  Native USB remains on IO19/IO20.",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def write_netlist(root: Path = ROOT) -> Path:
    output = root / "NETLIST.md"
    output.write_text(render_netlist(), encoding="utf-8")
    print(f"wrote {output.relative_to(root)}")
    return output


def populated_component(reference: str, component: tuple[Any, ...]) -> bool:
    """Return whether a design component belongs in assembly outputs."""
    return reference not in design.DNP and component[4] != "none"


def bom_groups() -> dict[tuple[Any, ...], list[str]]:
    """Group only components with completely identical purchasing metadata."""
    groups: dict[tuple[Any, ...], list[str]] = {}
    for reference, component in design.COMPONENTS.items():
        (
            value,
            footprint_library,
            footprint,
            lcsc,
            jlc_class,
            unit_cost,
            description,
            _pins,
        ) = component
        if not populated_component(reference, component):
            continue
        key = (
            value,
            footprint_library,
            footprint,
            lcsc,
            jlc_class,
            unit_cost,
            description,
        )
        groups.setdefault(key, []).append(reference)
    return groups


def write_bom(root: Path = ROOT) -> Path:
    output_directory = root / "bom"
    output_directory.mkdir(parents=True, exist_ok=True)
    output = output_directory / "BOM.csv"
    total = 0.0
    with output.open("w", newline="", encoding="utf-8") as bom_file:
        writer = csv.writer(bom_file, lineterminator="\n")
        writer.writerow(
            [
                "Comment",
                "Designator",
                "Footprint",
                "LCSC Part #",
                "JLC class",
                "Qty",
                "Unit cost (USD)",
                "Ext cost (USD)",
                "Description",
            ]
        )
        for key, references in bom_groups().items():
            (
                value,
                _footprint_library,
                footprint,
                lcsc,
                jlc_class,
                unit_cost,
                description,
            ) = key
            quantity = len(references)
            extended_cost = quantity * unit_cost
            total += extended_cost
            writer.writerow(
                [
                    value,
                    ",".join(references),
                    footprint,
                    lcsc,
                    jlc_class,
                    quantity,
                    f"{unit_cost:.3f}",
                    f"{extended_cost:.3f}",
                    description,
                ]
            )
    print(f"wrote {output.relative_to(root)} (parts/board ≈ ${total:.2f})")
    return output


def write_cpl(root: Path = ROOT) -> Path:
    """Generate the CPL from the placed board, importing pcbnew lazily."""
    import pcbnew

    board_path = root / "kicad" / "Esp32Tap.kicad_pcb"
    if not board_path.is_file():
        raise FileNotFoundError(
            f"cannot generate CPL; KiCad board does not exist: {board_path}"
        )
    board = pcbnew.LoadBoard(str(board_path))
    output_directory = root / "bom"
    output_directory.mkdir(parents=True, exist_ok=True)
    output = output_directory / "CPL-positions.csv"
    auxiliary_origin_x = 100.0
    auxiliary_origin_y = 155.0

    with output.open("w", newline="", encoding="utf-8") as cpl_file:
        writer = csv.writer(cpl_file, lineterminator="\n")
        writer.writerow(
            [
                "Designator",
                "Val",
                "Package",
                "Mid X",
                "Mid Y",
                "Rotation",
                "Layer",
            ]
        )
        footprints = sorted(
            board.GetFootprints(),
            key=lambda footprint: footprint.GetReference(),
        )
        for footprint in footprints:
            reference = footprint.GetReference()
            component = design.COMPONENTS.get(reference)
            if component is None or not populated_component(
                reference,
                component,
            ):
                continue
            position = footprint.GetPosition()
            x_position = pcbnew.ToMM(position.x) - auxiliary_origin_x
            y_position = auxiliary_origin_y - pcbnew.ToMM(position.y)
            writer.writerow(
                [
                    reference,
                    footprint.GetValue(),
                    footprint.GetFPID().GetLibItemName(),
                    f"{x_position:.3f}mm",
                    f"{y_position:.3f}mm",
                    f"{footprint.GetOrientationDegrees():.0f}",
                    "Top",
                ]
            )
    print(f"wrote {output.relative_to(root)}")
    return output


def main(arguments: list[str] | None = None) -> None:
    args = parse_args(arguments)
    design.validate()
    write_netlist()
    write_bom()
    if not args.skip_cpl:
        write_cpl()


if __name__ == "__main__":
    main()
