[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
ESP_IDF_SDKCONFIG_DEFAULTS = "/project/hardware/Esp32Tap/firmware/esp32_rs/sdkconfig.defaults.devkit"
ESP_IDF_TOOLS_INSTALL_DIR = "fromenv"
